AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 template for CloudBenchmark"
# TODO:
# - VPC
# - Key pair

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "SSH Key Pair Name"
  EC2InstanceType:
    Type: String
    Default: "t2.micro"
    Description: "Instance Type"
  AMIType:
    Type: String
    Default: "x86"
    Description: "x86 or arm"
  OutputS3:
    Type: String
    Description: "output target S3 bucket"

Mappings:
  AmazonLinux2AMI:
    ap-northeast-1:
      "x86": "ami-0a2de1c3b415889d2"
    ap-southeast-1:
      "x86": "ami-0b84d2c53ad5250c2"
    us-west-2:
      "x86": "ami-01bbe152bf19d0289"
      "arm": "ami-0f374ff3bc5bb0929"

Resources:
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !FindInMap [AmazonLinux2AMI, !Ref "AWS::Region", !Ref "AMIType"]
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
      - !Ref SSHSecurityGroup
      IamInstanceProfile: !Ref EC2Profile
      BlockDeviceMappings: 
        - DeviceName: "/dev/sdm"
          Ebs: 
            VolumeType: "gp2"
            DeleteOnTermination: "true"
            VolumeSize: "100"
      Tags:
        - Key: "Name"
          Value: "CloudBenchmarkTarget"

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
        
  EC2Profile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - Ref: EC2Role
        
  EC2Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "target-s3-write"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:*"
                Resource:
                  - !Sub "arn:aws:s3:::${OutputS3}"
                  - !Sub "arn:aws:s3:::${OutputS3}/*"

Outputs:
  InstanceID:
    Value: !Ref EC2Instance
  PublicIP:
    Value: !GetAtt EC2Instance.PublicIp
